version: '3.3'

services:
  main_proxy:
    image: harshac/nginx2
    ports:
      - "8443:443"
    networks:
      - application_default
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
    secrets:
      - site.key
      - site.crt
    configs:
      - source: maintainance_proxy.conf
        target: /etc/nginx/conf.d/default.conf

secrets:
  site.key:
    external: true
  site.crt:
    external: true

configs:
  maintainance_proxy.conf:
     external: true

networks:
  application_default:
    external: true
