version: '3.5'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"  
    networks:
      - application_default    
  bot:    
    image: "{{hub_org}}/{{image_name}}:{{image_tag}}"
    deploy:
      mode: replicated
      replicas: {{ bot_replicas }}
    networks:
      - application_default
    ports:
      - "5005:5005"
    environment:
      - TMP=TMP
networks:
  application_default:
    external: true
    