version: '3.5'
services:
  router:    
    image: "{{hub_org}}/{{image_name}}:{{image_tag}}"
    deploy:
      mode: replicated
      replicas: {{ router_replicas }}
    networks:
      - application_default
    ports:
      - "4000:4000"
      - "8443:8443"
    environment:
      - RASA_CORE_ENDPOINT=http://bot:5005/webhooks/rest/webhook
      - REDIS_HOST=redis
      - HTTPS_PATH_KEY=/run/secrets/site.key
      - HTTPS_PATH_CERT=/run/secrets/site.crt
      - HTTPS_PATH_CA=/run/secrets/site.ca
      - telemetry_endpoint=v1/telemetry
      - sunbird_api_auth_token={{ sunbird_api_auth_token }}
      - telemetry_service_url=https://{{ domain_name }}/api/data/
    secrets:
      - site.key
      - site.crt
      - site.ca
secrets:
  site.key:
    external: true
  site.crt:
    external: true
  site.ca:
    external: true
networks:
  application_default:
    external: true