---
apiVersion: v1
kind: Service
metadata:
  name: kong-api-internal-endpoint
  namespace: {{ namespace }}
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    nodePort: 30800
    targetPort: 8000
  selector:
    app: apimanager
