- name: install psycopg2
  package:
    name: python-psycopg2
    state: present

- name: Verifying db users are present else creating them
  include: databases.yml

- name: creating database
  include: users.yml

- name: Install postgres client to create schema from file
  apt:
    name: postgresql-client
    state: present
    update_cache: yes
