env: ntpstaging
env_name: "{{ env }}"
instance: staging
instance_name: ntp
cloud_storage_config_environment: staging

#### overriding variables
composite_search_indexer_container_count: 4
publish_pipeline_container_count: 3
publish_yarn_container_memory_mb: 2048
dialcode_keyspace_name: "{{env}}_dialcode_store"
plugin_media_base_url: "https://dev.diksha.gov.in"
content.media.base.url: "https://dev.diksha.gov.in"


## Mahesh have to come back on this
learning_content_h5p_library_path: https://s3.ap-south-1.amazonaws.com/ekstep-public-dev/content/templates/h5p-library-latest.zip

############## Common ######################

proto: https
domain_name: dev.diksha.gov.in
ekstep_domain_name: https://qa.ekstep.in 

#bootstrap
ssh_public_key_deployer: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCxFtOamSxFClzoMfLLZ0mFOxLPOxS80xYuP4HVrh5kjl+zZxNKYH+8bL/LuDxzAkRi87iUprpD6nFkDkKkodlFedwBerLd7gdZhJSd9vOsGHa3IbAprFrcEPugGRrkzVhnTpu9zg6nv9Qk3lI65+8oHm/WUy8L/zR7Bccz3E0ylQ/9wXlqvMEzfJ9c8K88fbtjAzveC3loa7RFLOzwS1yrddR7zFbJ9U2Tv3mbmW+7tArbJmzz57c/0gY1mE7sKS+2+8FdD5/jeN31ViysEDwQDISIFbOJO6B0sfuZKbfr7RKkjiJ2ROVzgKLEhyHJHqIM5RcDGZ4955myOnx81GnK0m0s2z1h3LgOcDgIPZVrpjXQq6K6fvXW8vJ9bVN+SG7hKEqx9pvRNCzCHGOV0wIbzTNFUsB+2sI1txM3ssOsuJq/dEcb940LWdXhAaOthtO2Gi0UrpWGoaXklvmyrpjLE7OxoXuQIRNk0ONBpJW5eQDv86wIiWGcfr4dn/9UkumnL7GBV4yGE9OUZcleFHStG9u1h0NiWpQjtrUeRG9f2xAXyrUaAVl3Q8sfRt9qoCLs+MZpRbzKPDesDizASHluOGrI86YZ4FUkS0iLu86jQekOmbmG77845rw0lcOvcw2UmCYrQqmrtUGaVWAAxWV3Mn7K3cSw58w1NYgEHIw9UQ== deployer@dikshastaging"
bootstrap_user: deployer
bootstrap_key_path: /var/lib/jenkins/secrets/deployer_ssh_key
###################### LP ############################

azure_public_container: ntp-content-staging
#azure_account_name: ntpstagingall
learnings:
  paths: ['/data', '/data/graphDB', '/data/logs', '/data/contentBundle', '/data/properties', '/home/learning/tmp', '/home/learning/platform']
  service_config: ['consumer-config.xml']

searchs:
  paths: ['/data', '/data/logs', '/data/contentBundle', '/data/properties', '/home/learning/tmp', '/home/learning/platform', '/home/learning/platform/search', '/home/learning/platform/service', '/home/learning/platform/service/logs' ]


environment_id: 20000000

###########  jenkinspipeline upload artifact ############
artifacts_container: artifacts
#artifact_azure_account_name: "dikshaartifactstore"
#artifact_azure_account_key: "{{ lp_vault_artifact_azure_account_key }}"

#neo4j_home: "{{learner_user_home}}/{{neo4j_dir}}/neo4j-enterprise-3.3.0"
neo4j_home: "{{learner_user_home}}/{{neo4j_dir}}/neo4j-enterprise-3.3.10-SNAPSHOT"
#neo4j_zip: neo4j-enterprise-3.3.0-unix.tar.gz     # neo4j enterprise version.zip present in the artifacts folder
neo4j_zip: neo4j-enterprise-3.3.10-SNAPSHOT-unix.tar.gz
neo4j_enterprise: "true"

## Cassandra-backup
cassandra_backup_azure_container_name: 
compositesearch_index_name: "compositesearch"

########
tr_secondary_route_events: "LOG,ERROR"

## over riding backup
#backup_azure_storage_account_name: ntpbackupsstaging
### overriding backup secret
#backup_azure_storage_access_key: "{{lp_vault_backup_azure_storage_secret}}"

youtube_app_name: fetch-youtube-license

########## For content tool ############
ekstep_env_name: qa
contenttool:
 source:
  url: https://qa.ekstep.in/api
 destination:
  url: http://11.3.3.20:8080/learning-service
  storage_type: azure

## Heap size update for learning-service
tomcat_init_mem: -Xms2048m
tomcat_max_mem: -Xmx4096m

sunbird_installation: Diksha_Stage
swarm_manager_lb_ip: 11.3.8.8

## kubernetes variables ### overriding swarm manager lb ip to private ingress ip ### 
private_ingressgateway_ip: "{{swarm_manager_lb_ip}}"
learner_service_base_url: "http://{{private_ingressgateway_ip}}/learner"  ## lp samza jobs
cert_service_base_url: "http://{{private_ingressgateway_ip}}/cert"    ### lp samza jobs
kp_content_service_base_url: "http://{{private_ingressgateway_ip}}/content"  ## lp samza jobs
cert_reg_service_base_url: "http://{{private_ingressgateway_ip}}/certreg"  ## lp samza jobs
kp_print_service_base_url: "http://{{private_ingressgateway_ip}}/print"  ## lp samza jobs
kp_search_service_base_url: "http://{{private_ingressgateway_ip}}/search" ## lp samza jobs
lms_service_base_url: "http://{{private_ingressgateway_ip}}/lms"  ## lp samza jobs
kp_dial_service_base_url: "http://{{private_ingressgateway_ip}}/dial"

####################### Release-2.9.0 Storage account variables #####################
sunbird_management_storage_account_name: dikshastagingmanagement
sunbird_artifact_storage_account_name: dikshaartifact
sunbird_public_storage_account_name: ntpstagingall

### adding this for flink jobs deployment
dockerhub: ntphub.azurecr.io
docker_registry: ntphub
imagepullsecrets: diksha-registry-secret
kubeconfig_path: /var/lib/jenkins/secrets/staging-dp-k8s.yaml

# dial service variables
learningservice_ip: 11.3.3.22
dial_service_generate_url: "{{kp_dial_service_base_url}}/dialcode/v3/generate"
dial_service_search_url: "{{kp_dial_service_base_url}}/dialcode/v3/search"


# publish pipleine job var
publish_pipeline_task_opts: "-Dfile.encoding=UTF8 -XX:-UseG1GC -Xmx800m"

# release-3.4.0
# Private storage account name
sunbird_private_storage_account_name: dikshastagingprivate

##release -3.8.0
plugin_container_name: ntp-content-staging
kp_schema_base_path: "{{proto}}://{{sunbird_public_storage_account_name}}.blob.core.windows.net/{{plugin_container_name}}/schemas/local"

##release-3.9.0
# Media content
media_service_azure_tenant: deepikaekstep.onmicrosoft.com
media_service_azure_subscription_id: 5af454cb-5087-411d-a651-2d7d6c1b93a1
media_service_azure_account_name: ntpstagingmedia
media_service_azure_resource_group_name: staging_all
media_service_azure_token_client_key: 07429c07-04f7-4c77-bd44-c79ce400a70f
media_service_azure_token_client_secret: skA/pWodOLPZF/ea0ee8fSlVZsfPljwQJBc9Eb1gfRw=
stream_base_url: "https://ntpstagingmedia-inct.streaming.media.azure.net"

#### learning-lb
lp_url: "http://{{ learningservice_ip }}:8080/learning-service"
kp_learning_service_base_url: "http://{{ learningservice_ip }}:8080/learning-service"

##Graylog var
send_logs_to_graylog: true

flink_job_names:
  activity-aggregate-updater:
    job_class_name: 'org.sunbird.job.aggregate.task.ActivityAggregateUpdaterStreamTask'
    replica: 2
    jobmanager_memory: 1024m
    taskmanager_memory: 1024m
    taskslots: 1
    cpu_requests: 0.3
  relation-cache-updater:
    job_class_name: 'org.sunbird.job.relationcache.task.RelationCacheUpdaterStreamTask'
    replica: 1
    jobmanager_memory: 1024m
    taskmanager_memory: 1024m
    taskslots: 1
    cpu_requests: 0.3
  post-publish-processor:
    job_class_name: 'org.sunbird.job.postpublish.task.PostPublishProcessorStreamTask'
    replica: 1
    jobmanager_memory: 1024m
    taskmanager_memory: 1024m
    taskslots: 1
    cpu_requests: 0.3
  certificate-generator:
    job_class_name: 'org.sunbird.job.task.CertificateGeneratorStreamTask'
    replica: 1
    jobmanager_memory: 1024m
    taskmanager_memory: 1024m
    taskslots: 1
    cpu_requests: 0.3
  post-certificate-processor:
    job_class_name: 'org.sunbird.job.task.PostCertificateProcessorStreamTask'
    replica: 1
    jobmanager_memory: 1024m
    taskmanager_memory: 1024m
    taskslots: 1
    cpu_requests: 0.3
  certificate-pre-processor:
    job_class_name: 'org.sunbird.job.task.CertificatePreProcessorStreamTask'
    replica: 1
    jobmanager_memory: 1024m
    taskmanager_memory: 1024m
    taskslots: 1
    cpu_requests: 0.3
  questionset-publish:
    job_class_name: 'org.sunbird.job.questionset.task.QuestionSetPublishStreamTask'
    replica: 1
    jobmanager_memory: 2048m
    taskmanager_memory: 2048m
    taskslots: 1
    cpu_requests: 0.3
  enrolment-reconciliation:
    job_class_name: 'org.sunbird.job.recounciliation.task.EnrolmentReconciliationStreamTask'
    replica: 2
    jobmanager_memory: 1024m
    taskmanager_memory: 1024m
    taskslots: 1
    cpu_requests: 0.3
  video-stream-generator:
    job_class_name: 'org.sunbird.job.videostream.task.VideoStreamGeneratorStreamTask'
    replica: 1
    jobmanager_memory: 1024m
    taskmanager_memory: 1024m
    taskslots: 1
    cpu_requests: 0.3
  search-indexer:
    job_class_name: 'org.sunbird.job.searchindexer.task.SearchIndexerStreamTask'
    replica: 1
    jobmanager_memory: 1024m
    taskmanager_memory: 1024m
    taskslots: 1
    cpu_requests: 0.3
  asset-enrichment:
    job_class_name: 'org.sunbird.job.assetenricment.task.AssetEnrichmentStreamTask'
    replica: 2
    jobmanager_memory: 1024m
    taskmanager_memory: 1024m
    taskslots: 1
    cpu_requests: 0.3
  audit-history-indexer:
    job_class_name: 'org.sunbird.job.audithistory.task.AuditHistoryIndexerStreamTask'
    replica: 1
    jobmanager_memory: 1024m
    taskmanager_memory: 1024m
    taskslots: 1
    cpu_requests: 0.3  
  collection-cert-pre-processor:
    job_class_name: 'org.sunbird.job.collectioncert.task.CollectionCertPreProcessorTask'
    replica: 1
    jobmanager_memory: 1024m
    taskmanager_memory: 1024m
    taskslots: 1
    cpu_requests: 0.3
  auto-creator-v2 :
    job_class_name: 'org.sunbird.job.task.AutoCreatorV2StreamTask'
    replica: 1
    jobmanager_memory: 1024m
    taskmanager_memory: 1024m
    taskslots: 1
    cpu_requests: 0.3
  collection-certificate-generator :
    job_class_name: 'org.sunbird.job.certgen.task.CertificateGeneratorStreamTask'
    replica: 1
    jobmanager_memory: 1024m
    taskmanager_memory: 1024m
    taskslots: 1
    cpu_requests: 0.3
  audit-event-generator:
    job_class_name: 'org.sunbird.job.auditevent.task.AuditEventGeneratorStreamTask'
    replica: 1
    jobmanager_memory: 1024m
    taskmanager_memory: 1024m
    taskslots: 1
    cpu_requests: 0.3
  content-publish:
    job_class_name: 'org.sunbird.job.content.task.ContentPublishStreamTask'
    replica: 1
    jobmanager_memory: 2048m
    taskmanager_memory: 2048m
    taskslots: 1
    cpu_requests: 0.3
  metrics-data-transformer:
    job_class_name: 'org.sunbird.job.metricstransformer.task.MetricsDataTransformerStreamTask'
    replica: 1
    jobmanager_memory: 1024m
    taskmanager_memory: 1024m
    taskslots: 1
    cpu_requests: 0.3
  mvc-indexer:
    job_class_name: 'org.sunbird.job.mvcindexer.task.MVCIndexerStreamTask'
    replica: 1
    jobmanager_memory: 1024m
    taskmanager_memory: 1024m
    taskslots: 1
    cpu_requests: 0.3
  content-auto-creator:
    job_class_name: 'org.sunbird.job.contentautocreator.task.ContentAutoCreatorStreamTask'
    replica: 1
    jobmanager_memory: 2048m
    taskmanager_memory: 2048m
    taskslots: 1
    cpu_requests: 0.3
  qrcode-image-generator:
    job_class_name: 'org.sunbird.job.qrimagegenerator.task.QRCodeImageGeneratorTask'
    replica: 1
    jobmanager_memory: 1024m
    taskmanager_memory: 1024m
    taskslots: 1
    cpu_requests: 0.3
  dialcode-context-updater:
    job_class_name: 'org.sunbird.job.dialcodecontextupdater.task.DialcodeContextUpdaterStreamTask'
    replica: 1
    jobmanager_memory: 1024m
    taskmanager_memory: 1024m
    taskslots: 1
    cpu_requests: 0.3
  merge-user-courses:
    job_class_name: 'org.sunbird.job.merge.user.courses.task.MergeUserCoursesStreamTask'
    replica: 1
    jobmanager_memory: 1024m
    taskmanager_memory: 1024m
    taskslots: 1
    cpu_requests: 0.3
  assessment-aggregator:
    job_class_name: 'org.sunbird.dp.assessment.task.AssessmentAggregatorStreamTask'
    replica: 1
    jobmanager_memory: 1024m
    taskmanager_memory: 1024m
    taskmanager_process_memory: 1700m
    jobmanager_process_memory: 1600m
    taskslots: 1
    cpu_requests: 0.3
    scale_enabled: false
  notification-job:
    job_class_name: 'org.sunbird.job.notification.task.NotificationStreamTask'
    replica: 1
    jobmanager_memory: 1024m
    taskmanager_memory: 1024m
    taskslots: 1
    cpu_requests: 0.3
  

activity_agg_window_shards: 1000
activity_agg_dedup_parallelism: 2
enrolment_complete_parallelism: 2
activity_agg_batch_interval: 60
activity_agg_batch_read_size: 1
activity_agg_batch_write_size: 10
activity_agg_dedup_index: 13
activity_agg_dedup_expiry: 604800

##release-4.1.0 var
vdn_domain_name: "vdn.diksha.gov.in"
source_base_url: "{{proto}}://{{vdn_domain_name}}/api"
cert_env_prefix: ntp-staging

#####Redis-metadata2##
metadata2_redis_host: "{{ groups['redis-metadata2'][0] }}"

###release-4.8.0 #####
collection_certificate_generator_enable_rc_certificate : "TRUE"
enable_suppress_exception : "TRUE"
enable_rc_certificate : "TRUE"

###Release-5.0.0 Var ##
###  Merge User Courses Job related Vars
merge_user_courses_consumer_parallelism: 1
merge_user_courses_parallelism: 1
merge_user_courses_course_batch_parallelism: 1
merge_user_courses_course_date_format: "yyyy-MM-dd HH:mm:ss:SSSZ"

###  Notification Job related Vars
notification_job_consumer_parallelism: 1
notification_job_parallelism: 1

### assessment-aggregator related vars
assessaggregator_parallelism: 1
assessaggregator_consumer_parallelism: 1
assessaggregator_downstream_parallelism: 1
assessaggregator_scoreaggregator_parallelism: 1
middleware_cassandra_courses_keyspace: sunbird_courses
middleware_cassandra_assessment_aggregator_table: assessment_aggregator
middleware_cassandra_assessment_question_type : question
middleware_cassandra_user_enrolments_table: user_enrolments
middleware_cassandra_user_activity_agg_table: user_activity_agg
content_read_api_host: "https://{{ domain_name }}"
content_read_api_endpoint: "/api/content/v1/read/"

##release-5.0.0 vars
sunbird_msg_91_auth: "{{ core_vault_msg_91_auth_key }}"
sunbird_mail_server_from_email: "support-preprod@ntp.net.in"
sunbird_notification_msg_default_sender: DIKAPP 
sunbird_mail_server_username: "apikey"
sunbird_mail_server_host: smtp.sendgrid.net
sunbird_mail_server_port: 587
