---
- hosts: local
  become: yes 
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
    - "{{inventory_dir}}/common.yml"
  roles:
    - custom-k8s
